sudo: required
dist: trusty

os: linux

language: c

compiler:
  - gcc

addons:
  apt:
    packages:
    - python3
    - python-pip
    - python3-pip

cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - /opt/wafservice

before_install:
  - if [ ! -d /opt/wafservice/openresty ]; then python3 install.py install openresty ; fi
  - sudo rm -rf /opt/wafservice/wafservice
  - sudo adduser --system --no-create-home --group nginx

install:
  - sudo python3 -m pip install -r test/requirements.txt
  - sudo python3 install.py install wafservice

before_script:
  - if [ ! -f /opt/wafservice/openresty/nginx/logs/error.log ]; then touch /opt/wafservice/openresty/nginx/logs/error.log;sudo chown nginx:nginx /opt/wafservice/openresty/nginx/logs/error.log ; fi
  - sudo /opt/wafservice/openresty/nginx/sbin/nginx
  - sudo /opt/wafservice/openresty/nginx/sbin/nginx -s stop
  - echo -e "127.0.0.1   a.vntest.com\n127.0.0.1   b.vntest.com\n127.0.0.1   c.vntest.com" | sudo tee -a /etc/hosts

script:
  - sudo python3 test/test.py
